steps:
- name: 'gcr.io/cloud-builders/go:debian'
  args: ['build', './cmd/kritis/signer']
  env: ['PROJECT_ROOT=github.com/grafeas/kritis']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: /bin/bash
  args:
    - -c
    - |
      cd integration/signer &&
      export PROJECT_ID=$PROJECT_ID
      export BUILD_ID=$BUILD_ID
      ./signer_int.sh