steps:
- name: 'gcr.io/cloud-builders/go'
  entrypoint: /bin/bash
  args:
    - -c
    - |
      ls -al
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: /bin/bash
  args:
    - -c
    - |
      ./signer_int.sh