apiVersion: kritis.grafeas.io/v1beta1
kind: VulnzSigningPolicy
metadata:
  name: my-vsp
spec:
  project: <ATTESTATION_PROJECT>
  noteReference: projects/<NOTE_PROJECT>/notes/<NOTE_ID>
  packageVulnerabilityRequirements:
    maximumSeverity: MEDIUM
    maximumFixNotAvailableSeverity: MEDIUM
    allowlistCVEs:
      - providers/goog-vulnz/notes/CVE-2017-1000082
      - providers/goog-vulnz/notes/CVE-2017-1000081
